config/routes.rb
Umbrella::Application.routes.draw do
  resources :parapluies do
    member do
      get :handle
    end
  end

end

app/models/handle.rb
class Handle < ActiveRecord::Base
  attr_accessible :material, :parapluie_id

  belongs_to :parapluie
end

app/models/parapluie.rb
class Parapluie < ActiveRecord::Base
  attr_accessible :colour, :foldable, :handle_type

  has_many :handles

  validates :colour,  :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/parapluies_controller.rb
class ParapluiesController < ApplicationController

  before_filter :load_parapluie, :only => [:show, :edit, :update, :destroy, :handle]

  def load_parapluie
    @parapluie = Parapluie.find(params[:id])
  end

  def index
    @parapluies = Parapluie.all
    @name = "Dan"
  end

  def new
    @parapluie = Parapluie.new
  end

  def create
    if @parapluie.save
      redirect_to @parapluie, notice: 'Parapluie was successfully created.' 
    else
      render action: "new"
    end
  end

  def update
    if @parapluie.update_attributes(params[:parapluie])
      redirect_to @parapluie, notice: 'Parapluie was successfully updated.'
    else
      render action: "edit"
    end  
  end

  def destroy
    @parapluie.destroy
    redirect_to parapluies_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parapluies_helper.rb
module ParapluiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Umbrella</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parapluies/_form.html.erb
<%= form_for(@parapluie) do |f| %>
  <% if @parapluie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parapluie.errors.count, "error") %> prohibited this parapluie from being saved:</h2>

      <ul>
      <% @parapluie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :colour %><br />
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :foldable %><br />
    <%= f.check_box :foldable %>
  </div>
  <div class="field">
    <%= f.label :handle_type %><br />
    <%= f.text_field :handle_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parapluies/edit.html.erb
<h1>Editing parapluie</h1>

<%= render 'form' %>

<%= link_to 'Show', @parapluie %> |
<%= link_to 'Back', parapluies_path %>

app/views/parapluies/handle.html.erb
<h1>Handle</h1>

app/views/parapluies/index.html.erb
<h1>Listing parapluies</h1>

<table>
  <tr>
    <th>Colour</th>
    <th>Foldable</th>
    <th>Handle type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parapluies.each do |parapluie| %>
  <tr>
    <td><%= parapluie.colour %></td>
    <td><%= parapluie.foldable %></td>
    <td><%= parapluie.handle_type %></td>
    <td><%= link_to 'Show', parapluie %></td>
    <td><%= link_to 'Edit', edit_parapluie_path(parapluie) %></td>
    <td><%= link_to 'Destroy', parapluie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parapluie', new_parapluie_path %>

app/views/parapluies/new.html.erb
<h1>New parapluie</h1>

<%= render 'form' %>

<%= link_to 'Back', parapluies_path %>

app/views/parapluies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Colour:</b>
  <%= @parapluie.colour %>
</p>

<p>
  <b>Foldable:</b>
  <%= @parapluie.foldable %>
</p>

<p>
  <b>Handle type:</b>
  <%= @parapluie.handle_type %>
</p>


<%= link_to 'Edit', edit_parapluie_path(@parapluie) %> |
<%= link_to 'Back', parapluies_path %>